#!/usr/bin/env python3
# -*- coding: utf-8

""" Publish JSON data generated by resol.py to MQTT broker."""
# Shall be called every minute to work correctly.
# Holger Mueller
# 2017/03/04 initial revision
# 2017/04/06 added HomA meta/unit settings, modified topic names and removed 'name' tags
# 2018/09/09 fixed TLS/SSL transport layer
# 2020/10/28 made script Python3 compatible
# 2024/07/29 added Home Assistant discovery config messages
# 2025/09/21 adapted to Home Assistant add-on structure

import sys
import json
import datetime
import os.path
import ssl
import paho.mqtt.client as mqtt
from paho.mqtt.enums import CallbackAPIVersion
import bashio_logging  # provides logging output like bashio, must be imported before logging #pylint: disable=unused-import
import logging  # pylint: disable=wrong-import-order
import mqtt_config  # gets host, port, user, pwd, ca_certs from Home Assistant config

try:
    with open("/data/options.json", "r", encoding="utf-8") as f:
        config = json.load(f)
except Exception as e:  # pylint: disable=broad-except
    logging.error("Loading Home Assistant configuration file: %s", e)
    sys.exit(1)
debug = config.get('debug')
device_name = config.get('device_name')  # e.g. "DeltaSol BX"
systemId = config.get("homa_system_id")  # e.g. "123456-solar"
device = config.get('homa_device')  # e.g. Solar
room = config.get('homa_room')  # e.g. Sensors
area = config.get('hass_area')  # e.g. Solar

# Reminder if HomA setup messages have been send, delete and restart to resend
init_file = "/dev/shm/homa_init."+ systemId

mqtt_arr = [
    {'field': 'Temperatur Sensor 1', 'unit': ' °C', 'topic': 'Kollektortemperatur',      'class': 'temperature'},
    {'field': 'Temperatur Sensor 2', 'unit': ' °C', 'topic': 'Speichertemperatur unten', 'class': 'temperature'},
    {'field': 'Temperatur Sensor 3', 'unit': ' °C', 'topic': 'Speichertemperatur Mitte', 'class': 'temperature'},
    {'field': 'Temperatur Sensor 4', 'unit': ' °C', 'topic': 'Ruecklauftemperatur',      'class': 'temperature'},
    {'field': 'PWM 1',               'unit': ' %',  'topic': 'Solarpumpe Drehzahl',      'class': 'power_factor'},
    {'field': 'Drehzahl Relais 2',   'unit': '',    'topic': 'Umschaltventil Position',  'class': '_int'},
    {'field': 'Systemzeit',          'unit': '',    'topic': 'Solar Zeit',               'class': '_datetime'},
]


def get_topic(t1 = None, t2 = None, t3 = None):
    """Create topic string."""
    topic = "/devices/"+ systemId
    if t1:
        topic += "/"+ t1
    if t2:
        topic += "/"+ t2
    if t3:
        topic += "/"+ t3
    logging.debug("get_topic(): '%s'", topic)
    return topic


def homa_init():
    """Publish HomA setup messages to MQTT broker."""
    if os.path.isfile(init_file):
        # exit right away if init file exists, to force reinit remove that file
        return
    logging.info("Publishing HomA setup data ...")
    # set room name
    mqttc.publish(get_topic("meta/room"), room, retain=True)
    # set device name
    mqttc.publish(get_topic("meta/name"), device, retain=True)
    # setup controls
    order = 0
    for mqtt_item in mqtt_arr:
        order += 1
        mqttc.publish(get_topic("controls", mqtt_item['topic'], "meta/type"), "text", retain=True)
        mqttc.publish(get_topic("controls", mqtt_item['topic'], "meta/order"), order, retain=True)
        mqttc.publish(get_topic("controls", mqtt_item['topic'], "meta/unit"), mqtt_item['unit'], retain=True)
        homeassistant_config(mqtt_item)
    # create init file
    file = open(init_file, 'w', encoding="utf-8")
    #file.write(data)
    file.close()


def homeassistant_config(mqtt_item):
    """Send the Home Assistant config messages to enable discovery"""
    object_id = systemId+"-"+mqtt_item['topic'].replace(" ", "-")
    payload = {
        "device_class":mqtt_item['class'],
        "state_topic":"/devices/"+systemId+"/controls/"+mqtt_item['topic'],
        "name":mqtt_item['topic'],
        "unique_id":object_id,
        "object_id":object_id,
        "device":{
            "identifiers":[systemId],
            "name":"Solar RESOL VBus",
            "manufacturer":"Citrin Solar",
            "model":device_name,
            "suggested_area":area
        }
    }
    if mqtt_item['class'] in ["temperature", "power_factor"]:
        payload['state_class'] = "measurement"
    # special treatment for _int
    if mqtt_item['class'] == "_int":
        del payload['device_class']
        payload['native_value'] = "int"
    # special treatment for _datetime
    if mqtt_item['class'] == "_datetime":
        del payload['device_class']
        payload['value_template'] = "{{ as_datetime(value) }}"
        payload['icon'] = "mdi:calendar-arrow-right"
    # set unit_of_measurement only if available
    if 'unit' in mqtt_item and mqtt_item['unit']:
        payload['unit_of_measurement'] = mqtt_item['unit'].strip()
    # set value_template only if available
    if 'template' in mqtt_item:
        payload['value_template'] = mqtt_item['template']
    topic = "homeassistant/sensor/"+object_id+"/config"
    mqttc.publish(topic, json.dumps(payload), retain=True)


def on_connect(client, userdata, flags, reason_code, properties):  # pylint: disable=unused-argument
    """The callback for when the client receives a CONNACK response from the broker."""
    logging.debug("on_connect(): Connected with result code %s", str(reason_code))

    # Subscribing in on_connect() means that if we lose the connection and
    # reconnect then subscriptions will be renewed.
    #client.subscribe("$SYS/#")


def on_message(client, userdata, msg):  # pylint: disable=unused-argument
    """The callback for when a PUBLISH message is received from the broker."""
    payload_str = msg.payload.decode("utf-8")  # payload is bytes since API version 2
    logging.debug("on_message(): "+ msg.topic+ ":"+ payload_str)


def on_publish(client, userdata, mid, reason_code, properties):  # pylint: disable=unused-argument
    """The callback for when a message is published to the broker."""
    logging.debug("on_publish(): message send %s", str(mid))


if debug:
    logging.getLogger().setLevel(logging.DEBUG)
    logging.info("Debug output enabled.")

# get current time
now = datetime.datetime.now()

# connect to MQTT broker
mqttc = mqtt.Client(callback_api_version=CallbackAPIVersion.VERSION2)
mqttc.on_connect = on_connect
mqttc.on_message = on_message
mqttc.on_publish = on_publish
if mqtt_config.ca_certs != "" and mqtt_config.ca_certs is not None:
    mqttc.tls_set(mqtt_config.ca_certs, certfile=None, keyfile=None, cert_reqs=ssl.CERT_REQUIRED, tls_version=ssl.PROTOCOL_TLSv1_2, ciphers=None)
mqttc.username_pw_set(mqtt_config.user, password=mqtt_config.pwd)
mqttc.connect(mqtt_config.host, port=mqtt_config.port)
mqttc.loop_start()

homa_init()  # setup HomA MQTT device and control settings

# Load JSON data passed to stdin
data = json.load(sys.stdin)
try:
    data = data[device_name]
except KeyError as e:
    logging.error("Didn't find device name %s: %s", device_name, e)
    sys.exit(1)

# 'Systemzeit' is always empty, set own time ...
#data['Systemzeit'] = now.strftime("%d.%m.%Y_%H:%M:%S")
data['Systemzeit'] = now.replace(microsecond=0).isoformat()

# update MQTT topics
for mqtt_dict in mqtt_arr:
    logging.debug("topic '%s' = '%s' = '%s'", mqtt_dict['topic'], mqtt_dict['field'], data[mqtt_dict['field']])
    mqttc.publish(get_topic("controls", mqtt_dict['topic']), data[mqtt_dict['field']], retain=True)

# wait until all queued topics are published
mqttc.loop_stop()
mqttc.disconnect()
